In [233]:
import numpy as np  ,pandas as pd , plotly.express as px
import plotly.io as pio
pio.templates.default = 'plotly'

## Data Loading

In [181]:
! pip install SQLAlchemy

Requirement already satisfied: SQLAlchemy in c:\users\clt\.conda\envs\data\lib\site-packages (2.0.49)
Requirement already satisfied: greenlet>=1 in c:\users\clt\.conda\envs\data\lib\site-packages (from SQLAlchemy) (3.4.0)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\clt\.conda\envs\data\lib\site-packages (from SQLAlchemy) (4.15.0)

In [182]:
! pip install pymysql

Requirement already satisfied: pymysql in c:\users\clt\.conda\envs\data\lib\site-packages (1.1.2)

In [183]:
from sqlalchemy import create_engine

conn = create_engine("mysql+pymysql://root:sqlPassword2026*@localhost:3306/newschema")

chunks = pd.read_sql(sql= 'select * from customers' , con= conn , chunksize= 100)

pd.concat(chunks, axis=0)

,customer_id,customer_name,gender,age,home_address,zip_code,city,state,country
0,1,Leanna Busson,Female,30,8606 Victoria TerraceSuite 560,5464,Johnstonhaven,Northern Territory,Australia
1,2,Zabrina Harrowsmith,Genderfluid,69,8327 Kirlin SummitApt. 461,8223,New Zacharyfort,South Australia,Australia
2,3,Shina Dullaghan,Polygender,59,269 Gemma SummitSuite 109,5661,Aliburgh,Australian Capital Territory,Australia
3,4,Hewet McVitie,Bigender,67,743 Bailey GroveSuite 141,1729,South Justinhaven,Queensland,Australia
4,5,Rubia Ashleigh,Polygender,30,48 Hyatt ManorSuite 375,4032,Griffithsshire,Queensland,Australia
...,...,...,...,...,...,...,...,...,...
95,996,Elvira Sarfati,Agender,59,0433 Armstrong HillSuite 974,7613,Lake Danielland,Tasmania,Australia
96,997,Dickie Grushin,Non-binary,30,04 Howell PassSuite 209,6950,Ellaborough,Tasmania,Australia
97,998,Rebecka Fabler,Polygender,32,72 Annabelle PassApt. 446,52,Kohlerberg,Queensland,Australia
98,999,Carita Vynarde,Polygender,30,170 Wilson AvenueApt. 577,7849,East Oscarfurt,Western Australia,Australia
99,1000,Mandel Fairbanks,Male,71,1671 Lauren KnollSuite 945,9012,Lake Audreyborough,Tasmania,Australia

In [184]:
from sqlalchemy import create_engine

conn = create_engine("mysql+pymysql://root:sqlPassword2026*@localhost:3306/newschema")

customers = pd.read_sql(sql= 'select * from customers' , con= conn)
products = pd.read_sql(sql= 'select * from products' , con= conn)
orders = pd.read_sql(sql= 'select * from orders' , con= conn)
sales = pd.read_sql(sql= 'select * from sales' , con= conn)

In [185]:
products

,product_ID,product_type,product_name,size,colour,quantity,description
0,0,Shirt,Oxford Cloth,XS,red,66,"A red coloured, XS sized, Oxford Cloth Shirt"
1,1,Shirt,Oxford Cloth,S,red,53,"A red coloured, S sized, Oxford Cloth Shirt"
2,2,Shirt,Oxford Cloth,M,red,54,"A red coloured, M sized, Oxford Cloth Shirt"
3,3,Shirt,Oxford Cloth,L,red,69,"A red coloured, L sized, Oxford Cloth Shirt"
4,4,Shirt,Oxford Cloth,XL,red,47,"A red coloured, XL sized, Oxford Cloth Shirt"
...,...,...,...,...,...,...,...
1255,1255,Trousers,Tracksuit Bottoms,XS,violet,67,"A violet coloured, XS sized, Tracksuit Bottoms..."
1256,1256,Trousers,Tracksuit Bottoms,S,violet,48,"A violet coloured, S sized, Tracksuit Bottoms ..."
1257,1257,Trousers,Tracksuit Bottoms,M,violet,73,"A violet coloured, M sized, Tracksuit Bottoms ..."
1258,1258,Trousers,Tracksuit Bottoms,L,violet,45,"A violet coloured, L sized, Tracksuit Bottoms ..."
1259,1259,Trousers,Tracksuit Bottoms,XL,violet,60,"A violet coloured, XL sized, Tracksuit Bottoms..."

In [186]:
orders

     order_id  customer_id  order_date delivery_date
0           1           64  30/08/2021    24/09/2021
1           2          473  03/02/2021    13/02/2021
2           3          774  08/10/2021    03/11/2021
3           4          433  06/05/2021    19/05/2021
4           5          441  23/03/2021    24/03/2021
..        ...          ...         ...           ...
995       996          345  13/01/2021    02/02/2021
996       997          346  18/01/2021    31/01/2021
997       998          407  05/05/2021    21/05/2021
998       999          428  15/06/2021    12/07/2021
999      1000          896  07/04/2021    24/04/2021

[1000 rows x 4 columns]

In [187]:
customers

,customer_id,customer_name,gender,age,home_address,zip_code,city,state,country
0,1,Leanna Busson,Female,30,8606 Victoria TerraceSuite 560,5464,Johnstonhaven,Northern Territory,Australia
1,2,Zabrina Harrowsmith,Genderfluid,69,8327 Kirlin SummitApt. 461,8223,New Zacharyfort,South Australia,Australia
2,3,Shina Dullaghan,Polygender,59,269 Gemma SummitSuite 109,5661,Aliburgh,Australian Capital Territory,Australia
3,4,Hewet McVitie,Bigender,67,743 Bailey GroveSuite 141,1729,South Justinhaven,Queensland,Australia
4,5,Rubia Ashleigh,Polygender,30,48 Hyatt ManorSuite 375,4032,Griffithsshire,Queensland,Australia
...,...,...,...,...,...,...,...,...,...
995,996,Elvira Sarfati,Agender,59,0433 Armstrong HillSuite 974,7613,Lake Danielland,Tasmania,Australia
996,997,Dickie Grushin,Non-binary,30,04 Howell PassSuite 209,6950,Ellaborough,Tasmania,Australia
997,998,Rebecka Fabler,Polygender,32,72 Annabelle PassApt. 446,52,Kohlerberg,Queensland,Australia
998,999,Carita Vynarde,Polygender,30,170 Wilson AvenueApt. 577,7849,East Oscarfurt,Western Australia,Australia
999,1000,Mandel Fairbanks,Male,71,1671 Lauren KnollSuite 945,9012,Lake Audreyborough,Tasmania,Australia

In [188]:
sales

      sales_id  order_id  product_id  price_per_unit  quantity  total_price
0            0         1         218             106         2          212
1            1         1         481             118         1          118
2            2         1           2              96         3          288
3            3         1        1002             106         2          212
4            4         1         691             113         3          339
...        ...       ...         ...             ...       ...          ...
4995      4995       998         321             109         2          218
4996      4996       998         251              95         3          285
4997      4997       999         872             113         1          113
4998      4998       999         998             106         2          212
4999      4999       999        1105             115         1          115

[5000 rows x 6 columns]

In [189]:
# We have import all four tables alone, and concat them using pandas 
# The second choice was use one sql statement to join all four in one query

### Data Preparation

- Merge / Join using Pandas

In [190]:
df = pd.merge(left= customers , right= orders , on='customer_id' , how= 'inner' )
df

,customer_id,customer_name,gender,age,home_address,zip_code,city,state,country,order_id,order_date,delivery_date
0,292,Aldin Moline,Male,25,7210 Farrell HillApt. 735,6426,West Aidenview,Victoria,Australia,209,08/05/2021,20/05/2021
1,20,Gigi Kalaher,Genderqueer,55,2069 Phoebe MallApt. 543,6318,East Audrey,South Australia,Australia,432,20/10/2021,03/11/2021
2,20,Gigi Kalaher,Genderqueer,55,2069 Phoebe MallApt. 543,6318,East Audrey,South Australia,Australia,641,10/03/2021,22/03/2021
3,419,Chaddie Fawlkes,Male,58,31 Towne SummitSuite 671,3887,West Mackenzie,Queensland,Australia,433,18/08/2021,02/09/2021
4,940,Jamesy Rennles,Genderqueer,46,835 Mayer ParkwaySuite 374,9769,Harberview,Tasmania,Australia,434,11/05/2021,01/06/2021
...,...,...,...,...,...,...,...,...,...,...,...,...
995,872,Brendis Blackboro,Non-binary,74,17 Beatty Station StApt. 918,7892,West Lukeshire,New South Wales,Australia,80,26/04/2021,20/05/2021
996,346,Kerianne Parris,Genderqueer,40,59 Bergstrom GroveSuite 260,6060,Olsonbury,Northern Territory,Australia,997,18/01/2021,31/01/2021
997,439,Daren Airs,Female,75,378 John MallSuite 835,3142,West Thomas,Victoria,Australia,905,11/01/2021,23/01/2021
998,407,Murdock Bulfit,Male,41,5233 Lara AvenueSuite 291,8697,Hartmannshire,Queensland,Australia,998,05/05/2021,21/05/2021
999,508,Jan Isenor,Non-binary,65,6863 Tremblay KnollSuite 290,9728,West Annaport,Northern Territory,Australia,394,06/09/2021,10/09/2021

In [191]:
df = pd.merge(left= df , right= sales ,on= 'order_id' , how= 'inner' )
df

,customer_id,customer_name,gender,age,home_address,zip_code,city,state,country,order_id,order_date,delivery_date,sales_id,product_id,price_per_unit,quantity,total_price
0,292,Aldin Moline,Male,25,7210 Farrell HillApt. 735,6426,West Aidenview,Victoria,Australia,209,08/05/2021,20/05/2021,1018,837,117,1,117
1,292,Aldin Moline,Male,25,7210 Farrell HillApt. 735,6426,West Aidenview,Victoria,Australia,209,08/05/2021,20/05/2021,1019,428,107,2,214
2,292,Aldin Moline,Male,25,7210 Farrell HillApt. 735,6426,West Aidenview,Victoria,Australia,209,08/05/2021,20/05/2021,1020,1220,105,1,105
3,292,Aldin Moline,Male,25,7210 Farrell HillApt. 735,6426,West Aidenview,Victoria,Australia,209,08/05/2021,20/05/2021,1021,29,96,2,192
4,20,Gigi Kalaher,Genderqueer,55,2069 Phoebe MallApt. 543,6318,East Audrey,South Australia,Australia,432,20/10/2021,03/11/2021,2145,191,98,3,294
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,508,Jan Isenor,Non-binary,65,6863 Tremblay KnollSuite 290,9728,West Annaport,Northern Territory,Australia,394,06/09/2021,10/09/2021,1963,179,98,1,98
4996,508,Jan Isenor,Non-binary,65,6863 Tremblay KnollSuite 290,9728,West Annaport,Northern Territory,Australia,394,06/09/2021,10/09/2021,1964,933,96,3,288
4997,508,Jan Isenor,Non-binary,65,6863 Tremblay KnollSuite 290,9728,West Annaport,Northern Territory,Australia,394,06/09/2021,10/09/2021,1965,537,98,3,294
4998,508,Jan Isenor,Non-binary,65,6863 Tremblay KnollSuite 290,9728,West Annaport,Northern Territory,Australia,394,06/09/2021,10/09/2021,1966,1004,106,3,318
4999,508,Jan Isenor,Non-binary,65,6863 Tremblay KnollSuite 290,9728,West Annaport,Northern Territory,Australia,394,06/09/2021,10/09/2021,1967,226,106,3,318

In [192]:
df = pd.merge(left= df , right= products ,left_on='product_id',
              right_on='product_ID', how='inner' )
df

,customer_id,customer_name,gender,age,home_address,zip_code,city,state,country,order_id,order_date,delivery_date,sales_id,product_id,price_per_unit,quantity_x,total_price,product_ID,product_type,product_name,size,colour,quantity_y,description
0,292,Aldin Moline,Male,25,7210 Farrell HillApt. 735,6426,West Aidenview,Victoria,Australia,209,08/05/2021,20/05/2021,1018,837,117,1,117,837,Jacket,Shearling,M,violet,74,"A violet coloured, M sized, Shearling Jacket"
1,292,Aldin Moline,Male,25,7210 Farrell HillApt. 735,6426,West Aidenview,Victoria,Australia,209,08/05/2021,20/05/2021,1019,428,107,2,214,428,Jacket,Denim,L,orange,73,"A orange coloured, L sized, Denim Jacket"
2,292,Aldin Moline,Male,25,7210 Farrell HillApt. 735,6426,West Aidenview,Victoria,Australia,209,08/05/2021,20/05/2021,1020,1220,105,1,105,1220,Trousers,Pleated,XS,violet,58,"A violet coloured, XS sized, Pleated Trousers"
3,292,Aldin Moline,Male,25,7210 Farrell HillApt. 735,6426,West Aidenview,Victoria,Australia,209,08/05/2021,20/05/2021,1021,29,96,2,192,29,Shirt,Oxford Cloth,XL,indigo,55,"A indigo coloured, XL sized, Oxford Cloth Shirt"
4,20,Gigi Kalaher,Genderqueer,55,2069 Phoebe MallApt. 543,6318,East Audrey,South Australia,Australia,432,20/10/2021,03/11/2021,2145,191,98,3,294,191,Shirt,Camp Collared,S,green,60,"A green coloured, S sized, Camp Collared Shirt"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,508,Jan Isenor,Non-binary,65,6863 Tremblay KnollSuite 290,9728,West Annaport,Northern Territory,Australia,394,06/09/2021,10/09/2021,1963,179,98,1,98,179,Shirt,Camp Collared,XL,red,79,"A red coloured, XL sized, Camp Collared Shirt"
4996,508,Jan Isenor,Non-binary,65,6863 Tremblay KnollSuite 290,9728,West Annaport,Northern Territory,Australia,394,06/09/2021,10/09/2021,1964,933,96,3,288,933,Trousers,Drawstring,L,blue,50,"A blue coloured, L sized, Drawstring Trousers"
4997,508,Jan Isenor,Non-binary,65,6863 Tremblay KnollSuite 290,9728,West Annaport,Northern Territory,Australia,394,06/09/2021,10/09/2021,1965,537,98,3,294,537,Jacket,Leather,M,yellow,77,"A yellow coloured, M sized, Leather Jacket"
4998,508,Jan Isenor,Non-binary,65,6863 Tremblay KnollSuite 290,9728,West Annaport,Northern Territory,Australia,394,06/09/2021,10/09/2021,1966,1004,106,3,318,1004,Trousers,Wool,XL,blue,41,"A blue coloured, XL sized, Wool Trousers"
4999,508,Jan Isenor,Non-binary,65,6863 Tremblay KnollSuite 290,9728,West Annaport,Northern Territory,Australia,394,06/09/2021,10/09/2021,1967,226,106,3,318,226,Shirt,Chambray,S,green,63,"A green coloured, S sized, Chambray Shirt"

- Handling quantity_x , quantity_y

In [193]:
df = df.rename(columns={'quantity_x' :'quantity', 'quantity_y' :'Stock'})
df

,customer_id,customer_name,gender,age,home_address,zip_code,city,state,country,order_id,order_date,delivery_date,sales_id,product_id,price_per_unit,quantity,total_price,product_ID,product_type,product_name,size,colour,Stock,description
0,292,Aldin Moline,Male,25,7210 Farrell HillApt. 735,6426,West Aidenview,Victoria,Australia,209,08/05/2021,20/05/2021,1018,837,117,1,117,837,Jacket,Shearling,M,violet,74,"A violet coloured, M sized, Shearling Jacket"
1,292,Aldin Moline,Male,25,7210 Farrell HillApt. 735,6426,West Aidenview,Victoria,Australia,209,08/05/2021,20/05/2021,1019,428,107,2,214,428,Jacket,Denim,L,orange,73,"A orange coloured, L sized, Denim Jacket"
2,292,Aldin Moline,Male,25,7210 Farrell HillApt. 735,6426,West Aidenview,Victoria,Australia,209,08/05/2021,20/05/2021,1020,1220,105,1,105,1220,Trousers,Pleated,XS,violet,58,"A violet coloured, XS sized, Pleated Trousers"
3,292,Aldin Moline,Male,25,7210 Farrell HillApt. 735,6426,West Aidenview,Victoria,Australia,209,08/05/2021,20/05/2021,1021,29,96,2,192,29,Shirt,Oxford Cloth,XL,indigo,55,"A indigo coloured, XL sized, Oxford Cloth Shirt"
4,20,Gigi Kalaher,Genderqueer,55,2069 Phoebe MallApt. 543,6318,East Audrey,South Australia,Australia,432,20/10/2021,03/11/2021,2145,191,98,3,294,191,Shirt,Camp Collared,S,green,60,"A green coloured, S sized, Camp Collared Shirt"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,508,Jan Isenor,Non-binary,65,6863 Tremblay KnollSuite 290,9728,West Annaport,Northern Territory,Australia,394,06/09/2021,10/09/2021,1963,179,98,1,98,179,Shirt,Camp Collared,XL,red,79,"A red coloured, XL sized, Camp Collared Shirt"
4996,508,Jan Isenor,Non-binary,65,6863 Tremblay KnollSuite 290,9728,West Annaport,Northern Territory,Australia,394,06/09/2021,10/09/2021,1964,933,96,3,288,933,Trousers,Drawstring,L,blue,50,"A blue coloured, L sized, Drawstring Trousers"
4997,508,Jan Isenor,Non-binary,65,6863 Tremblay KnollSuite 290,9728,West Annaport,Northern Territory,Australia,394,06/09/2021,10/09/2021,1965,537,98,3,294,537,Jacket,Leather,M,yellow,77,"A yellow coloured, M sized, Leather Jacket"
4998,508,Jan Isenor,Non-binary,65,6863 Tremblay KnollSuite 290,9728,West Annaport,Northern Territory,Australia,394,06/09/2021,10/09/2021,1966,1004,106,3,318,1004,Trousers,Wool,XL,blue,41,"A blue coloured, XL sized, Wool Trousers"
4999,508,Jan Isenor,Non-binary,65,6863 Tremblay KnollSuite 290,9728,West Annaport,Northern Territory,Australia,394,06/09/2021,10/09/2021,1967,226,106,3,318,226,Shirt,Chambray,S,green,63,"A green coloured, S sized, Chambray Shirt"

In [194]:
# To show all columns :

pd.set_option('display.max_columns' , None)

### Data Exploration

In [195]:
# Check Data Types
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 24 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   customer_id     5000 non-null   int64
 1   customer_name   5000 non-null   str
 2   gender          5000 non-null   str
 3   age             5000 non-null   int64
 4   home_address    5000 non-null   str
 5   zip_code        5000 non-null   int64
 6   city            5000 non-null   str
 7   state           5000 non-null   str
 8   country         5000 non-null   str
 9   order_id        5000 non-null   int64
 10  order_date      5000 non-null   str
 11  delivery_date   5000 non-null   str
 12  sales_id        5000 non-null   int64
 13  product_id      5000 non-null   int64
 14  price_per_unit  5000 non-null   int64
 15  quantity        5000 non-null   int64
 16  total_price     5000 non-null   int64
 17  product_ID      5000 non-null   int64
 18  product_type    5000 non-null   str
 19  product_name    5000 non-null   str
 20  size            5000 non-null   str
 21  colour          5000 non-null   str
 22  Stock           5000 non-null   int64
 23  description     5000 non-null   str
dtypes: int64(11), str(13)
memory usage: 1.7 MB

In [196]:
# Check Duplicates

df.duplicated().sum()

np.int64(0)

In [197]:
# Check summary statistics for Numerical Columns
df.describe().round(2)

,customer_id,age,zip_code,order_id,sales_id,product_id,price_per_unit,quantity,total_price,product_ID,Stock
count,5000.00,5000.00,5000.00,5000.00,5000.00,5000.00,5000.0,5000.00,5000.00,5000.00,5000.00
mean,504.56,48.76,4912.36,503.04,2499.50,634.05,103.5,1.99,206.36,634.05,60.08
std,276.50,17.58,2907.37,285.96,1443.52,363.26,9.2,0.81,86.36,363.26,11.68
min,1.00,20.00,52.00,1.00,0.00,1.00,90.0,1.00,90.00,1.00,40.00
25%,276.00,34.00,2273.00,258.00,1249.75,323.00,95.0,1.00,112.00,323.00,50.00
50%,509.00,48.00,4750.00,504.50,2499.50,635.00,102.0,2.00,204.00,635.00,60.00
75%,733.00,63.00,7460.25,749.00,3749.25,951.00,112.0,3.00,285.00,951.00,70.00
max,1000.00,80.00,9998.00,999.00,4999.00,1259.00,119.0,3.00,357.00,1259.00,80.00

In [198]:
# Check summary statistics for Categorical Columns
df.describe(include= 'object')

C:\Users\clt\AppData\Local\Temp\ipykernel_17036\926141938.py:2: Pandas4Warning:

For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.

,customer_name,gender,home_address,city,state,country,order_date,delivery_date,product_type,product_name,size,colour,description
count,5000,5000,5000,5000,5000,5000,5000,5000,5000,5000,5000,5000,5000
unique,616,8,616,604,8,1,291,304,3,35,5,7,1233
top,Kristofor Roos,Female,5567 Clarke MallApt. 756,Jordanside,South Australia,Australia,21/06/2021,12/09/2021,Trousers,Denim,M,blue,"A orange coloured, L sized, Flannel Shirt"
freq,37,712,37,37,718,5000,51,49,1683,273,1022,762,13

In [199]:
# Check Missing Values
df.isna().sum()

customer_id       0
customer_name     0
gender            0
age               0
home_address      0
zip_code          0
city              0
state             0
country           0
order_id          0
order_date        0
delivery_date     0
sales_id          0
product_id        0
price_per_unit    0
quantity          0
total_price       0
product_ID        0
product_type      0
product_name      0
size              0
colour            0
Stock             0
description       0
dtype: int64

## Data Cleaning

In [200]:
df.columns

Index(['customer_id', 'customer_name', 'gender', 'age', 'home_address',
       'zip_code', 'city', 'state', 'country', 'order_id', 'order_date',
       'delivery_date', 'sales_id', 'product_id', 'price_per_unit', 'quantity',
       'total_price', 'product_ID', 'product_type', 'product_name', 'size',
       'colour', 'Stock', 'description'],
      dtype='str')

In [201]:
# Drop Unnecessary Columns

df.drop(['customer_id', 'home_address', 'zip_code', 'country', 'order_id', 'product_id', 'product_ID', 'description'], axis= 1, inplace= True)

In [202]:
# Re-Check duplicates
df.duplicated().sum()

np.int64(0)

In [203]:
df.head()

,customer_name,gender,age,city,state,order_date,delivery_date,sales_id,price_per_unit,quantity,total_price,product_type,product_name,size,colour,Stock
0,Aldin Moline,Male,25,West Aidenview,Victoria,08/05/2021,20/05/2021,1018,117,1,117,Jacket,Shearling,M,violet,74
1,Aldin Moline,Male,25,West Aidenview,Victoria,08/05/2021,20/05/2021,1019,107,2,214,Jacket,Denim,L,orange,73
2,Aldin Moline,Male,25,West Aidenview,Victoria,08/05/2021,20/05/2021,1020,105,1,105,Trousers,Pleated,XS,violet,58
3,Aldin Moline,Male,25,West Aidenview,Victoria,08/05/2021,20/05/2021,1021,96,2,192,Shirt,Oxford Cloth,XL,indigo,55
4,Gigi Kalaher,Genderqueer,55,East Audrey,South Australia,20/10/2021,03/11/2021,2145,98,3,294,Shirt,Camp Collared,S,green,60

In [204]:
# Convert to datetime

df['order_date'] = pd.to_datetime(df['order_date'], dayfirst= True)
df['delivery_date'] = pd.to_datetime(df['delivery_date'], dayfirst= True)

In [205]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 16 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   customer_name   5000 non-null   str
 1   gender          5000 non-null   str
 2   age             5000 non-null   int64
 3   city            5000 non-null   str
 4   state           5000 non-null   str
 5   order_date      5000 non-null   datetime64[us]
 6   delivery_date   5000 non-null   datetime64[us]
 7   sales_id        5000 non-null   int64
 8   price_per_unit  5000 non-null   int64
 9   quantity        5000 non-null   int64
 10  total_price     5000 non-null   int64
 11  product_type    5000 non-null   str
 12  product_name    5000 non-null   str
 13  size            5000 non-null   str
 14  colour          5000 non-null   str
 15  Stock           5000 non-null   int64
dtypes: datetime64[us](2), int64(6), str(8)
memory usage: 973.1 KB

- In depth check for numerical columns

In [206]:
num_cols = df.select_dtypes(include= 'number').columns.drop('sales_id')
num_cols

Index(['age', 'price_per_unit', 'quantity', 'total_price', 'Stock'], dtype='str')

In [207]:
for col in num_cols:
    px.histogram(df, x= col , title=f'The Distribution of {col}').show()

- In depth check for categorical columns

In [208]:
cat_cols = df.select_dtypes(include= 'str').columns.drop('customer_name')
cat_cols

Index(['gender', 'city', 'state', 'product_type', 'product_name', 'size',
       'colour'],
      dtype='str')

In [209]:
for col in cat_cols:

    print(col)
    print(df[col].nunique())
    print(df[col].unique())
    print('-' * 100)

gender
8
<ArrowStringArray>
[       'Male', 'Genderqueer',  'Non-binary',    'Bigender',     'Agender',
 'Genderfluid',      'Female',  'Polygender']
Length: 8, dtype: str
----------------------------------------------------------------------------------------------------
city
604
<ArrowStringArray>
[  'West Aidenview',      'East Audrey',   'West Mackenzie',
       'Harberview',     'Thompsonport',    'New Beaumouth',
    'New Jadehaven',        'Sauerfort',    'Callumborough',
         'Colestad',
 ...
    'Port Isabelle',      'North Kayla',     'West Michael',
  'Rutherfordville',  'Port Davidburgh',       'Audreyfurt',
 'North Marcusland',        'Olsonbury',    'Hartmannshire',
    'West Annaport']
Length: 604, dtype: str
----------------------------------------------------------------------------------------------------
state
8
<ArrowStringArray>
[                    'Victoria',              'South Australia',
                   'Queensland',                     'Tasmania',
           'Northern Territory', 'Australian Capital Territory',
              'New South Wales',            'Western Australia']
Length: 8, dtype: str
----------------------------------------------------------------------------------------------------
product_type
3
<ArrowStringArray>
['Jacket', 'Trousers', 'Shirt']
Length: 3, dtype: str
----------------------------------------------------------------------------------------------------
product_name
35
<ArrowStringArray>
[        'Shearling',             'Denim',           'Pleated',
      'Oxford Cloth',     'Camp Collared',             'Coach',
           'Peacoat', 'Tracksuit Bottoms',             'Linen',
       'Relaxed Leg',            'Chinos',              'Polo',
            'Puffer',      'Cuban Collar',          'Pullover',
             'Parka',             'Cords',           'Flannel',
       'Trench Coat',           'Leather',      'High-Waisted',
          'Chambray',            'Henley',             'Dress',
       'Windbreaker',           'Joggers',   'Casual Slim Fit',
          'Cardigan',              'Wool',           'Cropped',
        'Drawstring',            'Bomber',       'Cargo Pants',
   'Mandarin Collar',          'Slim-Fit']
Length: 35, dtype: str
----------------------------------------------------------------------------------------------------
size
5
<ArrowStringArray>
['M', 'L', 'XS', 'XL', 'S']
Length: 5, dtype: str
----------------------------------------------------------------------------------------------------
colour
7
<ArrowStringArray>
['violet', 'orange', 'indigo', 'green', 'blue', 'red', 'yellow']
Length: 7, dtype: str
----------------------------------------------------------------------------------------------------

## Feature Engineering

In [210]:
df.head()

,customer_name,gender,age,city,state,order_date,delivery_date,sales_id,price_per_unit,quantity,total_price,product_type,product_name,size,colour,Stock
0,Aldin Moline,Male,25,West Aidenview,Victoria,2021-05-08,2021-05-20,1018,117,1,117,Jacket,Shearling,M,violet,74
1,Aldin Moline,Male,25,West Aidenview,Victoria,2021-05-08,2021-05-20,1019,107,2,214,Jacket,Denim,L,orange,73
2,Aldin Moline,Male,25,West Aidenview,Victoria,2021-05-08,2021-05-20,1020,105,1,105,Trousers,Pleated,XS,violet,58
3,Aldin Moline,Male,25,West Aidenview,Victoria,2021-05-08,2021-05-20,1021,96,2,192,Shirt,Oxford Cloth,XL,indigo,55
4,Gigi Kalaher,Genderqueer,55,East Audrey,South Australia,2021-10-20,2021-11-03,2145,98,3,294,Shirt,Camp Collared,S,green,60

In [211]:
df['delivery_days']= (df['delivery_date'] - df['order_date']).dt.days
df['delivery_days']

0       12
1       12
2       12
3       12
4       14
        ..
4995     4
4996     4
4997     4
4998     4
4999     4
Name: delivery_days, Length: 5000, dtype: int64

In [212]:
df['month'] = df['order_date'].dt.to_period('M').dt.to_timestamp()
df['month']

0      2021-05-01
1      2021-05-01
2      2021-05-01
3      2021-05-01
4      2021-10-01
          ...
4995   2021-09-01
4996   2021-09-01
4997   2021-09-01
4998   2021-09-01
4999   2021-09-01
Name: month, Length: 5000, dtype: datetime64[us]

In [213]:
df['age'].describe()

count    5000.000000
mean       48.760400
std        17.577519
min        20.000000
25%        34.000000
50%        48.000000
75%        63.000000
max        80.000000
Name: age, dtype: float64

In [214]:
# Create groups based on age range 
def age_group(x):
    if x <= 35:
        return 'Young'
    elif x <= 55:
        return 'Middle Aged'
    elif x > 55: 
        return 'Senior'
    
df['age group'] = df['age'].apply(age_group)

df['age group']

0             Young
1             Young
2             Young
3             Young
4       Middle Aged
           ...
4995         Senior
4996         Senior
4997         Senior
4998         Senior
4999         Senior
Name: age group, Length: 5000, dtype: str

In [215]:
df['order_date'].describe()

count                          5000
mean     2021-05-25 15:10:39.360000
min             2021-01-01 00:00:00
25%             2021-03-13 00:00:00
50%             2021-05-24 00:00:00
75%             2021-08-08 00:00:00
max             2021-10-24 00:00:00
Name: order_date, dtype: object

In [216]:
df.head()

,customer_name,gender,age,city,state,order_date,delivery_date,sales_id,price_per_unit,quantity,total_price,product_type,product_name,size,colour,Stock,delivery_days,month,age group
0,Aldin Moline,Male,25,West Aidenview,Victoria,2021-05-08,2021-05-20,1018,117,1,117,Jacket,Shearling,M,violet,74,12,2021-05-01,Young
1,Aldin Moline,Male,25,West Aidenview,Victoria,2021-05-08,2021-05-20,1019,107,2,214,Jacket,Denim,L,orange,73,12,2021-05-01,Young
2,Aldin Moline,Male,25,West Aidenview,Victoria,2021-05-08,2021-05-20,1020,105,1,105,Trousers,Pleated,XS,violet,58,12,2021-05-01,Young
3,Aldin Moline,Male,25,West Aidenview,Victoria,2021-05-08,2021-05-20,1021,96,2,192,Shirt,Oxford Cloth,XL,indigo,55,12,2021-05-01,Young
4,Gigi Kalaher,Genderqueer,55,East Audrey,South Australia,2021-10-20,2021-11-03,2145,98,3,294,Shirt,Camp Collared,S,green,60,14,2021-10-01,Middle Aged

In [217]:
df['customer_name'].nunique()

616

In [218]:
df['sales_id'].nunique()

5000

In [219]:
df['total_price'].sum()

np.int64(1031800)

In [135]:
df['total_price'].mean()

np.float64(206.36)

In [136]:
# Save data as CSV file

df.to_csv('Cleaned_df.csv' ,index= False )

## Deployment

In [137]:
import streamlit as st

In [138]:
%%writefile my_text.txt 

'Hello'

Overwriting my_text.txt

In [139]:
%%writefile app.py

import streamlit as st
from datetime import datetime

# Layout
st.set_page_config(layout= 'wide', page_title='EDA')
# HTML
st.markdown("<h1 style='text-align: center; color: white;'>Exploratory Data Analysis</h1>", unsafe_allow_html= True)


# Text Options
st.title("This is a Title")
st.header("This is a Header")
st.subheader("This is a Sub-Header")
st.write('#### This is a small text')


# Images internal/ external from web

st.image('FB_IMG_1643590896863.jpg')

# Videos / Audios same method  (internal/ external)


# Metric 
st.metric('Temperature' , '70 F' , '-1.2 F')

# Button
# st.button('Click Here')
if st.button('Click Here'):
    st.write('Button is clicked!')

# Checkbox
if st.checkbox('Click me'):
    st.write('Welcome to Streamlit 2')

# Selectbox
st.selectbox("Country", ['Egypt', 'KSA', 'Germany'])

# Radio
st.radio("Country", ['Egypt', 'KSA', 'Germany'])

# Multiselect
st.multiselect('Skills', ['python', 'sql', 'plotly', 'streamlit'])

# Numbers 

# number input
st.number_input('Age', min_value= 18, max_value= 80, step= 1)

# slider
st.slider('Years of experience', min_value= 1, max_value= 10, step= 1, value= 5)

# Date
st.date_input('Birthday', min_value= datetime(year= 1960, month= 1, day= 1))

st.sidebar.radio('Pages', ['Page 1', 'Page 2', 'Page 3'])

col1, col2, col3 = st.columns(3, vertical_alignment= 'center')

with col1:
    st.header('This is column 1')

with col2:
    st.header('This is column 2')

with col3:
    st.header('This is column 3')

# Tabs
tab1, tab2 = st.tabs(['Univariate Analysis', 'Bivariate Analysis'])

with tab1:
    st.write('Univariate Analysis')

with tab2:
    st.write('Multivariate Analysis')

Overwriting app.py

In [97]:
# Only run once 
! streamlit run app.py

^C

### Insights

- Which product category (product_type) has the highest total sales volume?

In [68]:
plot_df = df.groupby('product_type')['sales_id'].count().sort_values(ascending=False).reset_index()
plot_df

  product_type  sales_id
0     Trousers      1683
1       Jacket      1676
2        Shirt      1641

In [73]:
px.bar(data_frame= plot_df , x='product_type' , y= 'sales_id' , title='Total Orders per Product Category',
       labels={'product_type':'Product Type' , 'sales_id':'Total Orders'}, text_auto=True , color_discrete_sequence=['gray'])

- Which specific product (product_name) generated the most revenue?

In [79]:
plot_df = df.groupby('product_name')['total_price'].sum().sort_values(ascending=False).reset_index().head(10)
plot_df

      product_name  total_price
0            Denim        52399
1  Casual Slim Fit        36414
2      Trench Coat        35581
3        Shearling        35334
4           Puffer        35164
5          Flannel        33158
6          Cropped        32660
7          Pleated        32340
8          Joggers        31062
9         Chambray        30740

In [80]:
px.bar(data_frame= plot_df , x='product_name' , y= 'total_price' , title='Total Revenue per Product',
       labels={'product_name':'Product Name' , 'total_price':'Total Revenue'}, text_auto=True , color_discrete_sequence=['gray'])

- How do sales trends look on a monthly basis?

In [141]:
df['month'] = df['order_date'].dt.to_period('M').dt.to_timestamp()
df['month']

0      2021-05-01
1      2021-05-01
2      2021-05-01
3      2021-05-01
4      2021-10-01
          ...
4995   2021-09-01
4996   2021-09-01
4997   2021-09-01
4998   2021-09-01
4999   2021-09-01
Name: month, Length: 5000, dtype: datetime64[us]

In [87]:
df_sorted = df.sort_values(by= 'order_date')
df_sorted

,customer_name,gender,age,city,state,order_date,delivery_date,sales_id,price_per_unit,quantity,total_price,product_type,product_name,size,colour,Stock,delivery_days,month
2889,Anny Midden,Non-binary,32,Lake Amelia,Victoria,2021-01-01,2021-01-03,84,105,1,105,Shirt,Cuban Collar,XS,orange,62,2,2021-01-01
1696,Dunc Swynley,Genderqueer,20,Mullerberg,Western Australia,2021-01-01,2021-01-06,2859,94,2,188,Trousers,Cords,S,violet,65,5,2021-01-01
1695,Dunc Swynley,Genderqueer,20,Mullerberg,Western Australia,2021-01-01,2021-01-06,2858,106,2,212,Shirt,Chambray,XS,violet,47,5,2021-01-01
2697,Silas Chaman,Genderfluid,56,Gardenport,Victoria,2021-01-01,2021-01-05,3395,100,1,100,Jacket,Bomber,S,green,54,4,2021-01-01
2696,Silas Chaman,Genderfluid,56,Gardenport,Victoria,2021-01-01,2021-01-05,3394,90,3,270,Trousers,Relaxed Leg,S,red,70,4,2021-01-01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2773,Arlie Bowman,Genderqueer,34,Port Annabelle,Northern Territory,2021-10-24,2021-10-26,2458,90,1,90,Trousers,Relaxed Leg,M,orange,74,2,2021-10-01
2774,Arlie Bowman,Genderqueer,34,Port Annabelle,Northern Territory,2021-10-24,2021-10-26,2459,96,2,192,Shirt,Oxford Cloth,M,green,60,2,2021-10-01
2778,Arlie Bowman,Genderqueer,34,Port Annabelle,Northern Territory,2021-10-24,2021-10-26,2463,94,3,282,Trousers,Cords,XL,yellow,65,2,2021-10-01
2063,Waylen Swallwell,Non-binary,73,Sarahstad,Western Australia,2021-10-24,2021-11-20,3611,117,2,234,Jacket,Shearling,L,violet,61,27,2021-10-01
2775,Arlie Bowman,Genderqueer,34,Port Annabelle,Northern Territory,2021-10-24,2021-10-26,2460,105,3,315,Trousers,Pleated,M,indigo,48,2,2021-10-01

In [89]:
plot_df= df_sorted.groupby('month')['total_price'].sum().reset_index()
plot_df

       month  total_price
0 2021-01-01       119333
1 2021-02-01        95080
2 2021-03-01       131364
3 2021-04-01        97530
4 2021-05-01        85597
5 2021-06-01       101458
6 2021-07-01       116081
7 2021-08-01       104565
8 2021-09-01        96526
9 2021-10-01        84266

In [91]:
px.line(data_frame= plot_df , x= 'month' , y= 'total_price' , title='Total Revenue per Month' , markers= True)

In [ ]:
plot_df= df_sorted.groupby(['month', 'product_type'])['total_price'].sum().reset_index()
plot_df

        month product_type  total_price
0  2021-01-01       Jacket        42515
1  2021-01-01        Shirt        36501
2  2021-01-01     Trousers        40317
3  2021-02-01       Jacket        33704
4  2021-02-01        Shirt        27714
5  2021-02-01     Trousers        33662
6  2021-03-01       Jacket        45376
7  2021-03-01        Shirt        42469
8  2021-03-01     Trousers        43519
9  2021-04-01       Jacket        33790
10 2021-04-01        Shirt        33865
11 2021-04-01     Trousers        29875
12 2021-05-01       Jacket        30808
13 2021-05-01        Shirt        24040
14 2021-05-01     Trousers        30749
15 2021-06-01       Jacket        32337
16 2021-06-01        Shirt        35443
17 2021-06-01     Trousers        33678
18 2021-07-01       Jacket        38787
19 2021-07-01        Shirt        41213
20 2021-07-01     Trousers        36081
21 2021-08-01       Jacket        38281
22 2021-08-01        Shirt        32650
23 2021-08-01     Trousers        33634
24 2021-09-01       Jacket        35111
25 2021-09-01        Shirt        32285
26 2021-09-01     Trousers        29130
27 2021-10-01       Jacket        26317
28 2021-10-01        Shirt        27420
29 2021-10-01     Trousers        30529

In [ ]:
px.line(data_frame= plot_df , x= 'month' , y= 'total_price' , title='Total Revenue per Month' ,color= 'product_type', markers= True)

- What is the percentage of orders per state ?

In [226]:
plot_df =df.groupby('state')['sales_id'].count().sort_values(ascending=False).reset_index()
plot_df

                          state  sales_id
0               South Australia       718
1                    Queensland       687
2               New South Wales       647
3  Australian Capital Territory       638
4             Western Australia       604
5                      Victoria       591
6                      Tasmania       586
7            Northern Territory       529

In [234]:
px.pie(plot_df, names='state', values='sales_id' )

In [223]:
df.head()

,customer_name,gender,age,city,state,order_date,delivery_date,sales_id,price_per_unit,quantity,total_price,product_type,product_name,size,colour,Stock,delivery_days,month,age group
0,Aldin Moline,Male,25,West Aidenview,Victoria,2021-05-08,2021-05-20,1018,117,1,117,Jacket,Shearling,M,violet,74,12,2021-05-01,Young
1,Aldin Moline,Male,25,West Aidenview,Victoria,2021-05-08,2021-05-20,1019,107,2,214,Jacket,Denim,L,orange,73,12,2021-05-01,Young
2,Aldin Moline,Male,25,West Aidenview,Victoria,2021-05-08,2021-05-20,1020,105,1,105,Trousers,Pleated,XS,violet,58,12,2021-05-01,Young
3,Aldin Moline,Male,25,West Aidenview,Victoria,2021-05-08,2021-05-20,1021,96,2,192,Shirt,Oxford Cloth,XL,indigo,55,12,2021-05-01,Young
4,Gigi Kalaher,Genderqueer,55,East Audrey,South Australia,2021-10-20,2021-11-03,2145,98,3,294,Shirt,Camp Collared,S,green,60,14,2021-10-01,Middle Aged

## Customer Analysis
- Which age group makes the most purchases ?

In [236]:
plot_df = df['age group'].value_counts().reset_index()
plot_df

     age group  count
0       Senior   1958
1  Middle Aged   1589
2        Young   1453

In [237]:
px.pie(data_frame= plot_df, names= 'age group', values= 'count', title= 'Total Orders per each Age Group', hole= 0.6)

- Which state have the highest number of customer orders?

In [238]:
plot_df =df['state'].value_counts(ascending=True).reset_index()
plot_df

                          state  count
0            Northern Territory    529
1                      Tasmania    586
2                      Victoria    591
3             Western Australia    604
4  Australian Capital Territory    638
5               New South Wales    647
6                    Queensland    687
7               South Australia    718

In [239]:
px.bar(data_frame= plot_df, y= 'state', x= 'count', text_auto= True,
       labels= {'count' : 'Number of Orders', 'state' : 'State'}, title= 'Total Orders per State')

In [240]:
int(df['delivery_days'].mean().round())

14

In [164]:
df.columns

Index(['customer_name', 'gender', 'age', 'city', 'state', 'order_date',
       'delivery_date', 'sales_id', 'price_per_unit', 'quantity',
       'total_price', 'product_type', 'product_name', 'size', 'colour',
       'Stock', 'delivery_days', 'month', 'age group'],
      dtype='str')

In [241]:
plot_df=df['size'].value_counts().reset_index()
plot_df

  size  count
0    M   1022
1    L   1002
2   XS   1001
3    S    998
4   XL    977

In [242]:
px.pie(data_frame= plot_df, names= 'size', values= 'count', title= 'Percentage of each size volume', hole= 0.6)

- Which colors have the highest sales frequency per each age group ?

In [175]:
df.columns

Index(['customer_name', 'gender', 'age', 'city', 'state', 'order_date',
       'delivery_date', 'sales_id', 'price_per_unit', 'quantity',
       'total_price', 'product_type', 'product_name', 'size', 'colour',
       'Stock', 'delivery_days', 'month', 'age group'],
      dtype='str')

In [243]:
plot_df =  df.groupby(['colour', 'age group'])['sales_id'].count().reset_index()
plot_df

    colour    age group  sales_id
0     blue  Middle Aged       236
1     blue       Senior       310
2     blue        Young       216
3    green  Middle Aged       233
4    green       Senior       266
5    green        Young       195
6   indigo  Middle Aged       222
7   indigo       Senior       279
8   indigo        Young       225
9   orange  Middle Aged       208
10  orange       Senior       279
11  orange        Young       210
12     red  Middle Aged       218
13     red       Senior       264
14     red        Young       210
15  violet  Middle Aged       224
16  violet       Senior       311
17  violet        Young       204
18  yellow  Middle Aged       248
19  yellow       Senior       249
20  yellow        Young       193

In [246]:
px.bar(data_frame= plot_df, x= 'colour', y= 'sales_id', color= 'age group', barmode= 'group',
       labels= {'colour' : 'Colour', 'sales_id' : 'Count'}, title='Count of orders per each group for differebt colors')

- Top Products sold in each city for a spesific duration

In [255]:
# Add All cities option
df_all = df['city'].unique().tolist() + ['All Cities']
df_all

['West Aidenview',
 'East Audrey',
 'West Mackenzie',
 'Harberview',
 'Thompsonport',
 'New Beaumouth',
 'New Jadehaven',
 'Sauerfort',
 'Callumborough',
 'Colestad',
 'Port Hunter',
 'South Alexandraview',
 'Cassinport',
 'Stewartland',
 'East Piper',
 'Kaihaven',
 'Bartolettifurt',
 'North Aidentown',
 'West Hamish',
 'West Kai',
 'Russelstad',
 'Bauchton',
 'South Emilyborough',
 'Dietrichville',
 'Charlotteville',
 'Kaiview',
 'Beattychester',
 'Boyerland',
 'South Callum',
 'South Heidi',
 'South Hannahstad',
 'Georgiatown',
 'North Kaylastad',
 'New Angelina',
 'Port Jettshire',
 'East Matthewville',
 'North Lachlanfurt',
 'Ameliaview',
 'Sarahstad',
 'New George',
 'Lilystad',
 'Kiehnfurt',
 'Aliceland',
 'North Ruby',
 'Lake Callumville',
 'Miafort',
 'Lake Rose',
 'West Michaelport',
 'Violetborough',
 'North Elijahshire',
 'Adamsside',
 'South Hannah',
 'New Emmastad',
 'Sanfordborough',
 'Jordanborough',
 'South Evaport',
 'North Matthewfort',
 'Lake Nicholasfurt',
 'Cameronport',
 'Port Natalie',
 'New Ava',
 'South Chelseaton',
 'Port Aliview',
 'West Jessica',
 'Port Lily',
 'Taylorfurt',
 'Chasemouth',
 'Port Hannahburgh',
 'Port Madelineberg',
 'Harveyville',
 'Johnstonhaven',
 'Amyton',
 'Jacobport',
 'New Codyville',
 'West John',
 'West Danieltown',
 'North Riley',
 'Goodwinmouth',
 'West Sebastianfort',
 'East Alex',
 'South Alexview',
 'West Lucy',
 'Jordanside',
 'Abbeyshire',
 'Zacville',
 'Mollyland',
 'Noahmouth',
 'Calebville',
 'Port Blake',
 'East Sienna',
 'Abigailshire',
 'North Andrew',
 'East Xavier',
 'Daughertyport',
 'West Noah',
 'Sophiemouth',
 'North Lillian',
 'Siennabury',
 'Jettstad',
 'Kuhntown',
 'Port Chelseaport',
 'New Benjaminborough',
 'Rubyfort',
 'Charlotteborough',
 'West Grace',
 'South Nathan',
 'Mitchellhaven',
 'Masonfurt',
 'Port Sarah',
 'Abbottburgh',
 'Lake Declanland',
 'Zacharybury',
 'New Sophie',
 'West Ellaport',
 'South Maxland',
 'East Chelsea',
 'Samuelland',
 'Callummouth',
 'New Madisonborough',
 'Port Joshualand',
 'North Ellabury',
 'Trompview',
 'Krisland',
 'Scottview',
 'South Clairetown',
 'South Holly',
 'North Edwardshire',
 'East Jasper',
 'Jasmineville',
 'Lucyport',
 'West Stella',
 'Reillyborough',
 'Chloeville',
 'Swiftfort',
 'Kaifort',
 'Kulasville',
 'East Chasehaven',
 'Gleasonport',
 'North Avabury',
 'Baileyberg',
 'Lake Lillyville',
 'Lake Bellahaven',
 'Gleasonburgh',
 'Port Molly',
 'Josephmouth',
 'Claudiaview',
 'Crooksshire',
 'Towneport',
 'Port Ashtonhaven',
 'Jasperside',
 'Port Ellaside',
 'East Emily',
 'Lake William',
 'Lake Nicholasfort',
 'Grimesstad',
 'West Isla',
 'Aidenton',
 'Edwardtown',
 'Elijahshire',
 'Lake Aiden',
 'Hallhaven',
 'Schneiderstad',
 'East Mason',
 'Harveyside',
 'Boyleberg',
 'New Alyssa',
 'Ernserland',
 'Kaylafurt',
 'Shieldsside',
 'West Lukeshire',
 'Declanton',
 'Angelinaville',
 'West Zoe',
 'Port Anna',
 'Lake Owen',
 'Cameronton',
 'New Rileybury',
 'Davidtown',
 'Bergefort',
 'Lake Alihaven',
 'Emilymouth',
 'Reillyfurt',
 'West Eviebury',
 'Port Joshuaside',
 'North Mia',
 'South Hugoberg',
 'Huelhaven',
 'Marcusshire',
 'Langfort',
 'Cooperbury',
 'Rodriguezbury',
 'West Bella',
 'West Aidanton',
 'North Ivy',
 'South Tylermouth',
 'Lake Oliverberg',
 'New Callum',
 'Samuelside',
 'Lake Phoenixside',
 'Sofiaberg',
 'Hamiltonport',
 'West Finnberg',
 'East Imogen',
 'Amberland',
 'Lake Jesse',
 'Port Harrychester',
 'Lake Charli',
 'North Jasperville',
 'Isaacberg',
 'New Masonstad',
 'Violetfort',
 'Hallshire',
 'Lake Matildaville',
 'Port Alyssa',
 'Harrismouth',
 'Lukefurt',
 'Lake Elijah',
 'New Emilyton',
 'Oscarberg',
 'Tylershire',
 'South Declan',
 'Stokestown',
 'Levihaven',
 'Port Abigail',
 'New Oliverside',
 'Ellieshire',
 "O'connertown",
 'New Hannah',
 'Lincolnbury',
 'West Thomas',
 'Port Michael',
 'North Lukeshire',
 'West Hayleyhaven',
 'Lake Hannah',
 'Doylebury',
 'Lake Alice',
 'Georgeland',
 'Durgantown',
 'Hettingerfort',
 'New Callumtown',
 'Port Elliechester',
 'New Harry',
 'South Anthonyburgh',
 'Port Annabelle',
 'East George',
 'Smythland',
 'New Masonport',
 'New Mayaburgh',
 'South Levi',
 'East Max',
 'Port Aaronton',
 'Hannahberg',
 'Leomouth',
 'Port Chloe',
 "O'keefeton",
 'Mayaview',
 'Joelland',
 'Port Sophia',
 'Haydentown',
 'Spencerborough',
 'Islamouth',
 'Parisianmouth',
 'Mullerberg',
 'Port Ali',
 'Shieldschester',
 'West Amber',
 'South Charles',
 'West Alyssa',
 'North Nicholaston',
 "O'reillychester",
 'Gracemouth',
 'Youngview',
 'Lake Lucas',
 'Kiehnchester',
 'South Gabriel',
 'West Olivertown',
 'West Siennaland',
 'Chelseaview',
 'Baumbachtown',
 'Alexandraville',
 'West Cooper',
 'North Sophie',
 'West Alyssaton',
 'East Zacharystad',
 'Kreigerbury',
 'Angelinastad',
 'Port Ella',
 'Laraview',
 'West Annaton',
 'West Phoenix',
 'Angelinaport',
 'West Claudia',
 'Lake Abigailhaven',
 'West Callumside',
 'Joelburgh',
 'West Madison',
 'Lake Amelia',
 'Josephland',
 'Kulasmouth',
 'Bartolettiside',
 'Lincolnchester',
 'North Liamfort',
 'Port Zoeborough',
 'West Benjaminberg',
 'Lake Addisonland',
 'Thompsonbury',
 'West Jonathanshire',
 'Olivershire',
 'Port Alanamouth',
 'New Sienna',
 'Port Lillian',
 'South Pipermouth',
 'Samanthaberg',
 'Sofiahaven',
 'Alexanderland',
 'West Chasemouth',
 'Dickensshire',
 'Muellerfurt',
 'Hoppetown',
 'Alexandramouth',
 'East Michaelmouth',
 'Robertstown',
 'Handborough',
 'New Jayden',
 'Elijahburgh',
 'Gabrielville',
 'New Aidenfurt',
 'Lake Edward',
 'Amelieburgh',
 'Port Adamburgh',
 'Annaton',
 'Laylabury',
 'Casperfurt',
 'Chelseahaven',
 'Andersonburgh',
 'Lake Lukeberg',
 'West Dylanport',
 'Ellashire',
 'Port Kiara',
 'Michaelfurt',
 'South Claudialand',
 'Lake Mitchellbury',
 'Port Marcusshire',
 'Lake Madelineton',
 'East Aidan',
 'Sanfordberg',
 'East Hayden',
 'Port Christopher',
 'West Elliestad',
 'Ebertfurt',
 'Blakemouth',
 'Johnstonshire',
 'Fadelland',
 'West Marcus',
 'Davidshire',
 'East Marcus',
 'Hackettland',
 'South Ellieburgh',
 'Ryanberg',
 'Lake Johnchester',
 'Maxberg',
 'Mayerland',
 'North Paige',
 'North Mikayla',
 'Hermistonside',
 'Beahanport',
 'Samanthatown',
 'Lake Mikaylashire',
 'Kohlerberg',
 'East Declanside',
 'Sebastianbury',
 'Huelfort',
 'Gardenport',
 'New Stellastad',
 'Port Isabellafurt',
 'Bayermouth',
 'West Cameron',
 'New Alexchester',
 'Carterbury',
 'North Emmashire',
 'Macdonaldtown',
 'Andrewborough',
 'Ryanfurt',
 'Farrellchester',
 'Port Cody',
 'East Lillyville',
 'West Addison',
 'East Mackenzietown',
 'Hansenberg',
 'Wildermanside',
 'Hamiltonshire',
 'New Ruby',
 'Haleybury',
 'Codyview',
 'Fayburgh',
 'Phoebeberg',
 'North Caitlin',
 'Fadelburgh',
 'East Ruby',
 'Jademouth',
 'New Matildaville',
 'Hamishview',
 'Hackettchester',
 'Kiehnstad',
 'Matthewstad',
 'Williammouth',
 'West Rubyland',
 'Lake Ashleyhaven',
 'West Lachlan',
 'West Aaron',
 'Lake Gabriella',
 'Audreyport',
 'Hicklebury',
 'Lake Jacobborough',
 'Zacshire',
 'Port Jade',
 'Port Liam',
 'Justinport',
 'North Beau',
 'Morissetteborough',
 'Port Claudia',
 'South Rileyview',
 'Willowmouth',
 'Kreigerberg',
 'Port Jordan',
 'Richardshaven',
 'Codyfort',
 'Lewiston',
 'Baumbachton',
 'North Sophieland',
 'Macdonaldchester',
 'South Sophieview',
 'Johnsonstad',
 'East Charlesfurt',
 'Andersonchester',
 'Howehaven',
 'Lake Alanafort',
 'Beiermouth',
 'North Isabelleside',
 'West Ashley',
 'Madisonland',
 'East Madison',
 'West Joelmouth',
 'Gardenchester',
 'Walshland',
 'South Xavierport',
 'Lake Owenfurt',
 'Charlesshire',
 'Beahanfurt',
 'East Sophia',
 'South Georgia',
 'Feeneymouth',
 'Violetstad',
 'New Charlieville',
 'Lake Lincoln',
 'Langworthville',
 'Lake Danielland',
 'Lake Laurenview',
 'South Adam',
 'East Jakeberg',
 'Port Logan',
 'Gabriellatown',
 'West Bailey',
 'South Tyler',
 'North Jessica',
 'Maddisonmouth',
 'West Sophie',
 'New Isaac',
 'Port Siennaport',
 'Eliburgh',
 'Walterland',
 'Port Rosemouth',
 'West Kiara',
 'South Codyhaven',
 'West Isabelton',
 'West Jackfort',
 'Port Lillianside',
 'North Sebastianberg',
 'Lake Mollyburgh',
 'North Stephanie',
 'New Jackson',
 'Thomaschester',
 'East Joshua',
 'Evastad',
 'North Gracetown',
 'Hermistonberg',
 'Lake Phoebe',
 'South Jayden',
 'Port Eveland',
 'Laurenview',
 'East Isla',
 'Joelmouth',
 'Connellyport',
 'South Logan',
 'Monahanside',
 'Turcottetown',
 'Port Isabel',
 'Sanfordton',
 'Jordanburgh',
 'Donnellyfort',
 'Blakeborough',
 'South Cameron',
 'Imogenmouth',
 'Port Sebastianland',
 'South Eveshire',
 'Hoppeville',
 'New Mollystad',
 'Monahanberg',
 'New Leah',
 'Hudsonberg',
 'Jaydenside',
 'South Jasper',
 'West Audreyhaven',
 'South Zacmouth',
 'West Justin',
 'Jaspermouth',
 'Port Lucas',
 'Liamton',
 'Michaelberg',
 'Tillmanview',
 'Lake Paigemouth',
 'Conroychester',
 'Jacobsshire',
 'Lachlanstad',
 'East Kaylabury',
 'Heaneyview',
 'North Mackenzieborough',
 'Barrowschester',
 'Sophiafurt',
 'Lake Evemouth',
 'New Chase',
 'Davidfurt',
 'Nathanfort',
 'Port Haydenchester',
 'Abbottbury',
 'Johnschester',
 'Kingmouth',
 'New Kai',
 'Kaiberg',
 'Bauchland',
 'Kiehnburgh',
 'Schneiderbury',
 'North Alex',
 'Walkertown',
 'Lake Audreyborough',
 'North Josephmouth',
 'Lake Haydenton',
 'Thomasborough',
 'Lake Aidan',
 'Hollyfort',
 'Caitlinview',
 'Lake Michaelbury',
 'Lake Gabrielview',
 'Port Joeltown',
 'Hudsontown',
 'Graceville',
 'New Angelinaberg',
 'West Luke',
 'Isabellaton',
 'North Justin',
 'Harryburgh',
 'Leofurt',
 'North Scarlettborough',
 "D'amoreborough",
 'Braunhaven',
 'Port Madison',
 'Jacobsland',
 'North Cody',
 'Pipershire',
 'Wilsonside',
 'North Baileyside',
 'Hellermouth',
 'Lake Sienna',
 'Beahantown',
 'Walterstad',
 'East Benjamin',
 'West Zoeberg',
 'Haydenhaven',
 'East Sofia',
 'Eveside',
 'New Ellieland',
 'Lake Matilda',
 'East Gabriel',
 'New Beau',
 'West Baileyville',
 'Christopherside',
 'Lake Alicefurt',
 'East Lauren',
 'Taylorburgh',
 'Zacharyborough',
 'Evansburgh',
 'Stantonmouth',
 'South Tobyton',
 'Savannahland',
 'Port Isabelle',
 'North Kayla',
 'West Michael',
 'Rutherfordville',
 'Port Davidburgh',
 'Audreyfurt',
 'North Marcusland',
 'Olsonbury',
 'Hartmannshire',
 'West Annaport',
 'All Cities']

In [247]:
df.head()

,customer_name,gender,age,city,state,order_date,delivery_date,sales_id,price_per_unit,quantity,total_price,product_type,product_name,size,colour,Stock,delivery_days,month,age group
0,Aldin Moline,Male,25,West Aidenview,Victoria,2021-05-08,2021-05-20,1018,117,1,117,Jacket,Shearling,M,violet,74,12,2021-05-01,Young
1,Aldin Moline,Male,25,West Aidenview,Victoria,2021-05-08,2021-05-20,1019,107,2,214,Jacket,Denim,L,orange,73,12,2021-05-01,Young
2,Aldin Moline,Male,25,West Aidenview,Victoria,2021-05-08,2021-05-20,1020,105,1,105,Trousers,Pleated,XS,violet,58,12,2021-05-01,Young
3,Aldin Moline,Male,25,West Aidenview,Victoria,2021-05-08,2021-05-20,1021,96,2,192,Shirt,Oxford Cloth,XL,indigo,55,12,2021-05-01,Young
4,Gigi Kalaher,Genderqueer,55,East Audrey,South Australia,2021-10-20,2021-11-03,2145,98,3,294,Shirt,Camp Collared,S,green,60,14,2021-10-01,Middle Aged

In [249]:
df['order_date'].max()

Timestamp('2021-10-24 00:00:00')

In [260]:
df[df['city'].isin(['East Audrey','West Aidenview'])]

,customer_name,gender,age,city,state,order_date,delivery_date,sales_id,price_per_unit,quantity,total_price,product_type,product_name,size,colour,Stock,delivery_days,month,age group
0,Aldin Moline,Male,25,West Aidenview,Victoria,2021-05-08,2021-05-20,1018,117,1,117,Jacket,Shearling,M,violet,74,12,2021-05-01,Young
1,Aldin Moline,Male,25,West Aidenview,Victoria,2021-05-08,2021-05-20,1019,107,2,214,Jacket,Denim,L,orange,73,12,2021-05-01,Young
2,Aldin Moline,Male,25,West Aidenview,Victoria,2021-05-08,2021-05-20,1020,105,1,105,Trousers,Pleated,XS,violet,58,12,2021-05-01,Young
3,Aldin Moline,Male,25,West Aidenview,Victoria,2021-05-08,2021-05-20,1021,96,2,192,Shirt,Oxford Cloth,XL,indigo,55,12,2021-05-01,Young
4,Gigi Kalaher,Genderqueer,55,East Audrey,South Australia,2021-10-20,2021-11-03,2145,98,3,294,Shirt,Camp Collared,S,green,60,14,2021-10-01,Middle Aged
5,Gigi Kalaher,Genderqueer,55,East Audrey,South Australia,2021-10-20,2021-11-03,2146,93,1,93,Jacket,Coach,M,blue,54,14,2021-10-01,Middle Aged
6,Gigi Kalaher,Genderqueer,55,East Audrey,South Australia,2021-10-20,2021-11-03,2147,109,2,218,Jacket,Peacoat,XL,violet,42,14,2021-10-01,Middle Aged
7,Gigi Kalaher,Genderqueer,55,East Audrey,South Australia,2021-10-20,2021-11-03,2148,96,1,96,Shirt,Oxford Cloth,S,orange,72,14,2021-10-01,Middle Aged
8,Gigi Kalaher,Genderqueer,55,East Audrey,South Australia,2021-03-10,2021-03-22,3177,112,1,112,Trousers,Tracksuit Bottoms,XL,blue,68,12,2021-03-01,Middle Aged
9,Gigi Kalaher,Genderqueer,55,East Audrey,South Australia,2021-03-10,2021-03-22,3178,96,1,96,Shirt,Oxford Cloth,XS,indigo,61,12,2021-03-01,Middle Aged
10,Gigi Kalaher,Genderqueer,55,East Audrey,South Australia,2021-03-10,2021-03-22,3179,91,2,182,Shirt,Linen,S,blue,77,12,2021-03-01,Middle Aged
11,Gigi Kalaher,Genderqueer,55,East Audrey,South Australia,2021-03-10,2021-03-22,3180,90,1,90,Trousers,Relaxed Leg,XL,blue,40,12,2021-03-01,Middle Aged
12,Gigi Kalaher,Genderqueer,55,East Audrey,South Australia,2021-03-10,2021-03-22,3181,113,3,339,Trousers,Chinos,XS,red,69,12,2021-03-01,Middle Aged
2167,Aldin Moline,Male,25,West Aidenview,Victoria,2021-05-09,2021-06-05,4150,91,1,91,Shirt,Linen,XL,indigo,66,27,2021-05-01,Young
2168,Aldin Moline,Male,25,West Aidenview,Victoria,2021-05-09,2021-06-05,4151,113,1,113,Trousers,Chinos,L,violet,62,27,2021-05-01,Young
2169,Aldin Moline,Male,25,West Aidenview,Victoria,2021-05-09,2021-06-05,4152,94,1,94,Shirt,Henley,L,yellow,62,27,2021-05-01,Young
2170,Aldin Moline,Male,25,West Aidenview,Victoria,2021-05-09,2021-06-05,4153,96,1,96,Trousers,Drawstring,XL,orange,68,27,2021-05-01,Young
2171,Aldin Moline,Male,25,West Aidenview,Victoria,2021-05-09,2021-06-05,4154,100,3,300,Jacket,Bomber,XL,indigo,50,27,2021-05-01,Young
2172,Aldin Moline,Male,25,West Aidenview,Victoria,2021-05-09,2021-06-05,4155,118,1,118,Jacket,Puffer,L,violet,49,27,2021-05-01,Young
2173,Aldin Moline,Male,25,West Aidenview,Victoria,2021-05-09,2021-06-05,4156,112,3,336,Jacket,Cardigan,XL,orange,75,27,2021-05-01,Young
2174,Aldin Moline,Male,25,West Aidenview,Victoria,2021-05-09,2021-06-05,4157,109,2,218,Jacket,Peacoat,S,red,67,27,2021-05-01,Young
2175,Aldin Moline,Male,25,West Aidenview,Victoria,2021-05-09,2021-06-05,4158,106,1,106,Trousers,Wool,M,violet,51,27,2021-05-01,Young

In [ ]:
plot_df= df['product_name'].value_counts().reset_index()
plot_df

         product_name  count
0               Denim    273
1             Joggers    164
2     Casual Slim Fit    154
3            Slim-Fit    154
4           Shearling    150
5              Bomber    150
6             Pleated    147
7          Drawstring    147
8        Oxford Cloth    146
9         Relaxed Leg    146
10        Trench Coat    146
11             Henley    146
12           Pullover    143
13        Windbreaker    143
14            Flannel    141
15           Chambray    141
16             Puffer    140
17       High-Waisted    140
18      Camp Collared    139
19            Leather    136
20             Chinos    135
21            Cropped    135
22              Coach    134
23              Parka    134
24           Cardigan    134
25        Cargo Pants    134
26            Peacoat    132
27              Linen    131
28               Polo    131
29  Tracksuit Bottoms    130
30              Dress    127
31              Cords    126
32               Wool    125
33    Mandarin Collar    124
34       Cuban Collar    122

In [ ]:
df.to_csv('Cleaned_df.csv' ,index= False )

In [2]:
import pipreqs

! pipreqs .

WARNING: Import named "numpy" not found locally. Trying to resolve it at the PyPI server.
WARNING: Import named "numpy" was resolved to "numpy:2.4.4" package (https://pypi.org/project/numpy/).
Please, verify manually the final list of requirements.txt to avoid possible dependency confusions.
WARNING: Import named "pandas" not found locally. Trying to resolve it at the PyPI server.
WARNING: Import named "pandas" was resolved to "pandas:3.0.2" package (https://pypi.org/project/pandas/).
Please, verify manually the final list of requirements.txt to avoid possible dependency confusions.
INFO: Successfully saved requirements file in .\requirements.txt